-- Baseline do schema JurisFlow para bancos PostgreSQL vazios.
-- Derivada da captura aprovada em 2026-07-20 (PostgreSQL 18.4).
-- Contem somente DDL: nenhum dado de negocio faz parte desta migration.

CREATE TABLE public.auditoria (
    id bigint NOT NULL,
    acao character varying(80) NOT NULL,
    data_hora timestamp(6) with time zone NOT NULL,
    descricao character varying(300),
    detalhes character varying(1000),
    entidade character varying(80),
    entidade_id bigint,
    ip character varying(64),
    sucesso boolean NOT NULL,
    user_agent character varying(500),
    usuario_email character varying(254),
    usuario_id bigint,
    usuario_nome character varying(160)
);

ALTER TABLE public.auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cliente (
    id bigint NOT NULL,
    cpf_cnpj character varying(255),
    email character varying(255),
    endereco character varying(255),
    nome character varying(255),
    status character varying(255),
    telefone character varying(255),
    area_juridica character varying(255),
    tipo_cliente character varying(255),
    bairro character varying(255),
    cep character varying(255),
    cidade character varying(255),
    complemento character varying(255),
    data_cadastro character varying(255),
    data_nascimento character varying(255),
    estado character varying(255),
    estado_civil character varying(255),
    obs_rapida character varying(255),
    observacoes character varying(255),
    profissao character varying(255),
    rg character varying(255),
    sexo character varying(255),
    telefone_secundario character varying(255),
    whatsapp character varying(255),
    ativo boolean,
    data_exclusao timestamp(6) with time zone,
    motivo_exclusao character varying(255)
);

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.compromisso (
    id bigint NOT NULL,
    data character varying(255),
    descricao character varying(255),
    hora character varying(255),
    prioridade character varying(255),
    status character varying(255),
    tipo character varying(255),
    titulo character varying(255),
    cliente_id bigint,
    processo_id bigint,
    chave_integracao character varying(255),
    origem character varying(255)
);

ALTER TABLE public.compromisso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compromisso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.documentos (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    categoria character varying(255),
    chave_armazenamento character varying(255) NOT NULL,
    content_type character varying(255) NOT NULL,
    data_exclusao timestamp(6) with time zone,
    data_upload timestamp(6) with time zone NOT NULL,
    descricao character varying(2000),
    extensao character varying(12) NOT NULL,
    nome_original character varying(255) NOT NULL,
    tamanho_bytes bigint NOT NULL,
    titulo character varying(255) NOT NULL,
    cliente_id bigint,
    processo_id bigint,
    usuario_exclusao_id bigint,
    usuario_upload_id bigint
);

ALTER TABLE public.documentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.honorario (
    id bigint NOT NULL,
    competencia character varying(255),
    descricao character varying(255),
    forma_pagamento character varying(255),
    status character varying(255),
    tipo_honorario character varying(255),
    valor_total numeric(15,2),
    cliente_id bigint,
    processo_id bigint,
    acrescimos numeric(15,2),
    chave_integracao character varying(255),
    data_cadastro character varying(255),
    desconto numeric(15,2),
    observacoes_internas character varying(255),
    origem character varying(255),
    responsavel character varying(255),
    valor_bruto numeric(15,2)
);

ALTER TABLE public.honorario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.honorario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.parcela_honorario (
    id bigint NOT NULL,
    data_cadastro character varying(255),
    data_recebimento date,
    numero_parcela integer NOT NULL,
    status character varying(255),
    valor_previsto numeric(15,2) NOT NULL,
    valor_recebido numeric(15,2),
    vencimento date,
    honorario_id bigint NOT NULL
);

ALTER TABLE public.parcela_honorario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parcela_honorario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.processo (
    id bigint NOT NULL,
    area_juridica character varying(255),
    comarca character varying(255),
    data_abertura character varying(255),
    data_audiencia character varying(255),
    descricao character varying(255),
    forma_pagamento character varying(255),
    juiz character varying(255),
    numero character varying(255),
    parcelas_honorario integer,
    prazo_final character varying(255),
    prioridade character varying(255),
    status character varying(255),
    status_financeiro character varying(255),
    tipo_acao character varying(255),
    tribunal character varying(255),
    ult_movimentacao character varying(255),
    valor_causa double precision,
    valor_honorario double precision,
    vara character varying(255),
    vencimento_honorario character varying(255),
    cliente_id bigint,
    data_cadastro character varying(255),
    ativo boolean,
    data_exclusao timestamp(6) with time zone,
    motivo_exclusao character varying(255)
);

ALTER TABLE public.processo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.processo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.recebimento_honorario (
    id bigint NOT NULL,
    data_cadastro timestamp(6) with time zone NOT NULL,
    data_cancelamento timestamp(6) with time zone,
    data_recebimento date NOT NULL,
    forma_pagamento character varying(255) NOT NULL,
    motivo_cancelamento character varying(255),
    observacao character varying(255),
    status character varying(255) NOT NULL,
    valor_recebido numeric(15,2) NOT NULL,
    honorario_id bigint NOT NULL
);

ALTER TABLE public.recebimento_honorario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recebimento_honorario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    data_atualizacao timestamp(6) with time zone NOT NULL,
    data_cadastro timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    perfil character varying(255) NOT NULL,
    senha_hash character varying(255) NOT NULL,
    CONSTRAINT usuarios_perfil_check CHECK (((perfil)::text = ANY ((ARRAY['ADMIN'::character varying, 'ADVOGADO'::character varying, 'ASSISTENTE'::character varying])::text[])))
);

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.auditoria
    ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.compromisso
    ADD CONSTRAINT compromisso_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.honorario
    ADD CONSTRAINT honorario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.parcela_honorario
    ADD CONSTRAINT parcela_honorario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.processo
    ADD CONSTRAINT processo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.recebimento_honorario
    ADD CONSTRAINT recebimento_honorario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.honorario
    ADD CONSTRAINT uk15arsct7d1x6p7rffnoagne1a UNIQUE (chave_integracao);

ALTER TABLE ONLY public.parcela_honorario
    ADD CONSTRAINT uk_parcela_honorario_numero UNIQUE (honorario_id, numero_parcela);

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT ukep92c6sn70jhl32rwp3h7ctbu UNIQUE (chave_armazenamento);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);

ALTER TABLE ONLY public.compromisso
    ADD CONSTRAINT ukmroxf66ynav3te13k33mbv237 UNIQUE (chave_integracao);

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);

CREATE INDEX idx_auditoria_acao ON public.auditoria USING btree (acao);
CREATE INDEX idx_auditoria_data_hora ON public.auditoria USING btree (data_hora);
CREATE INDEX idx_auditoria_usuario_id ON public.auditoria USING btree (usuario_id);
CREATE INDEX idx_parcela_honorario ON public.parcela_honorario USING btree (honorario_id);
CREATE INDEX idx_recebimento_honorario ON public.recebimento_honorario USING btree (honorario_id);
CREATE INDEX idx_recebimento_honorario_data ON public.recebimento_honorario USING btree (data_recebimento);

ALTER TABLE ONLY public.recebimento_honorario
    ADD CONSTRAINT fk1twam3dptk65p8dfcyb9nj1i1 FOREIGN KEY (honorario_id) REFERENCES public.honorario(id);

ALTER TABLE ONLY public.honorario
    ADD CONSTRAINT fk8kfxqtiuqlp70m08pw159989j FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);

ALTER TABLE ONLY public.parcela_honorario
    ADD CONSTRAINT fk912mnmijlst41ykohtohybhmg FOREIGN KEY (honorario_id) REFERENCES public.honorario(id);

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fk9abextl9fbo1tfkqf2cbtvsvv FOREIGN KEY (usuario_exclusao_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.processo
    ADD CONSTRAINT fka41q3lwla2epn0nrcbslxsapx FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fkd04ts9tacxfb0sdfi55by3njn FOREIGN KEY (usuario_upload_id) REFERENCES public.usuarios(id);

ALTER TABLE ONLY public.honorario
    ADD CONSTRAINT fkd5tn7jby3e422q5jh2v98hn0c FOREIGN KEY (processo_id) REFERENCES public.processo(id);

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fkfax9j4g7ku3xb088u5itugavs FOREIGN KEY (processo_id) REFERENCES public.processo(id);

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fkhk6nl7q598qv4a94jbbbl9lac FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);

ALTER TABLE ONLY public.compromisso
    ADD CONSTRAINT fknugnkhf4sa56x8iciim61mohq FOREIGN KEY (processo_id) REFERENCES public.processo(id);

ALTER TABLE ONLY public.compromisso
    ADD CONSTRAINT fkqonwv1nnc9px9jipvvk92fyfy FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
